# Generated by Django 2.0 on 2018-09-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Bloodgroup',
            field=models.CharField(choices=[('op', 'O+'), ('ap', 'A+'), ('bp', 'B+'), ('abp', 'AB+')], default='op', max_length=2, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2, verbose_name='Gender'),
        ),
    ]
