# Generated by Django 2.0 on 2018-09-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_detail', '0002_auto_20180923_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Bloodgroup',
            new_name='blood_group',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Dob',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Mobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default=1, max_length=25, verbose_name='Address'),
            preserve_default=False,
        ),
    ]
